# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint.xdc

# IP: ip/fpu_mul/fpu_mul.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_mul || ORIG_REF_NAME==fpu_mul} -quiet] -quiet

# IP: ip/fpu_fused/fpu_fused.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_fused || ORIG_REF_NAME==fpu_fused} -quiet] -quiet

# IP: ip/fpu_add/fpu_add.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_add || ORIG_REF_NAME==fpu_add} -quiet] -quiet

# IP: ip/fpu_sub/fpu_sub.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_sub || ORIG_REF_NAME==fpu_sub} -quiet] -quiet
