// =============================================================================
// fp_add_sub.sv — IEEE 754 Double-Precision Add / Subtract Wrapper
// =============================================================================
// Wraps Xilinx Floating Point IP v7.1 (fp_add_sub_dp), generated by:
//   scripts/vivado/create_fp_ips.tcl
//
// Operation:
//   is_sub = 0  →  result = a + b
//   is_sub = 1  →  result = a - b
//
// Interface:
//   - Assert valid_in HIGH for exactly 1 cycle while a, b, is_sub are stable.
//   - valid_out pulses HIGH exactly FP_ADDSUB_LATENCY cycles later.
//   - result is valid on the cycle valid_out is HIGH.
//
// IP configuration:
//   Operation_Type        = Add_Subtract
//   A/B/Result Precision  = Double (64-bit)
//   Flow_Control          = NonBlocking
//   Has_Operation_Pinout  = true
//   C_Latency             = 11  (must match `FP_ADDSUB_LATENCY)
// =============================================================================

`include "fp_pkg.svh"

module fp_add_sub (
    input  logic        clk,
    input  logic        valid_in,   // pulse HIGH 1 cycle to start
    input  logic [63:0] a,
    input  logic [63:0] b,
    input  logic        is_sub,     // 0 = add, 1 = subtract
    output logic [63:0] result,
    output logic        valid_out
);

    // Xilinx FP IP: fp_add_sub_dp
    // Generated by create_fp_ips.tcl → fp_add_sub_dp.xci
    fp_add_sub_dp fp_add_sub_dp_i (
        .aclk                    (clk),
        // Operand A
        .s_axis_a_tvalid         (valid_in),
        .s_axis_a_tdata          (a),
        // Operand B
        .s_axis_b_tvalid         (valid_in),
        .s_axis_b_tdata          (b),
        // Operation select: [0]=0 → Add, [0]=1 → Subtract
        .s_axis_operation_tvalid (valid_in),
        .s_axis_operation_tdata  ({7'b0, is_sub}),
        // Result
        .m_axis_result_tvalid    (valid_out),
        .m_axis_result_tdata     (result)
    );

endmodule
