// =============================================================================
// fp_compare.sv — IEEE 754 Double-Precision Greater-Than Comparator Wrapper
// =============================================================================
// Wraps Xilinx Floating Point IP v7.1 (fp_gt_dp), generated by:
//   scripts/vivado/create_fp_ips.tcl
//
// Computes: a_gt_b = (a > b)
//
// Derived comparisons (zero cost, no extra IP needed):
//   a <  b  →  fp_compare(b, a).a_gt_b
//   a >= b  →  ~fp_compare(b, a).a_gt_b    [i.e., !(b > a)]
//   a <= b  →  ~fp_compare(a, b).a_gt_b    [i.e., !(a > b)]
//
// Interface:
//   - Assert valid_in HIGH for exactly 1 cycle while a, b are stable.
//   - valid_out pulses HIGH exactly FP_CMP_LATENCY cycles later.
//   - a_gt_b is valid on the cycle valid_out is HIGH.
//
// IP configuration:
//   Operation_Type       = Compare
//   C_Compare_Operation  = Greater_Than
//   A/B Precision        = Double (64-bit)
//   Flow_Control         = NonBlocking
//   C_Latency            = 2  (must match `FP_CMP_LATENCY)
// =============================================================================

`include "fp_pkg.svh"

module fp_compare (
    input  logic        clk,
    input  logic        valid_in,
    input  logic [63:0] a,
    input  logic [63:0] b,
    output logic        a_gt_b,     // 1 when a > b
    output logic        valid_out
);

    logic [7:0] result_data;

    // Xilinx FP IP: fp_gt_dp
    // m_axis_result_tdata[0] = 1 when condition (a > b) is TRUE
    fp_gt_dp fp_gt_dp_i (
        .aclk                 (clk),
        .s_axis_a_tvalid      (valid_in),
        .s_axis_a_tdata       (a),
        .s_axis_b_tvalid      (valid_in),
        .s_axis_b_tdata       (b),
        .m_axis_result_tvalid (valid_out),
        .m_axis_result_tdata  (result_data)
    );

    assign a_gt_b = result_data[0];

endmodule
