// =============================================================================
// fp_mul.sv — IEEE 754 Double-Precision Multiplier Wrapper
// =============================================================================
// Wraps Xilinx Floating Point IP v7.1 (fp_mul_dp), generated by:
//   scripts/vivado/create_fp_ips.tcl
//
// Interface:
//   - Assert valid_in HIGH for exactly 1 cycle while a, b are stable.
//   - valid_out pulses HIGH exactly FP_MUL_LATENCY cycles later.
//   - result is valid on the cycle valid_out is HIGH.
//
// IP configuration:
//   Operation_Type        = Multiply
//   A/B/Result Precision  = Double (64-bit)
//   Flow_Control          = NonBlocking
//   C_Latency             = 6  (must match `FP_MUL_LATENCY)
// =============================================================================

`include "fp_pkg.svh"

module fp_mul (
    input  logic        clk,
    input  logic        valid_in,
    input  logic [63:0] a,
    input  logic [63:0] b,
    output logic [63:0] result,
    output logic        valid_out
);

    // Xilinx FP IP: fp_mul_dp
    fp_mul_dp fp_mul_dp_i (
        .aclk                 (clk),
        .s_axis_a_tvalid      (valid_in),
        .s_axis_a_tdata       (a),
        .s_axis_b_tvalid      (valid_in),
        .s_axis_b_tdata       (b),
        .m_axis_result_tvalid (valid_out),
        .m_axis_result_tdata  (result)
    );

endmodule
